name: Continuous Integration - Release
on: 
  pull_request:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
    - name: Check out code
      uses: actions/checkout@v6
    - name: Create GitHub release
      run: gh release create "${{ github.ref_name }}" --generate-notes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
